### ISSUE TITLE
Initial seeds disappears after running the seed:migrate

### ISSUE THREAD

**Issue by suthanbala** [pboling/seed_migration#53]
**Issue**

- Initial seeds are contained in the `seeds.rb`. The code were contained inside the `ActiveRecord::Base.transaction do` and `end`
- When ran the `rake seed:migrate`, it did the migration, it added the timestamp like the following `SeedMigration::Migrator.bootstrap(20170309193307)`. However, it has removed all the seed code from the file. There were no reference to these initial contents anymore.
- When I try to run the `rake db:reset`, then `rake seed:migrate`, the it doesn't pull the data back anymore.

**Comment by pjambet** [comment]
Hi,

Sorry for the late reply, I don't exactly know what I changed but I apparently muted the notifications from this repo by mistake and didn't notice new issues opened in the last 6 months. Sorry about that.

Thanks for the bug report. I don't have a lot of time so I doubt that I'll get a chance to work on a fix but feel free to open a PR. I'll happily review it.

**Comment by pboling** [comment]
Closing in favor of #51
