### ISSUE TITLE
rake db:reset then rake db:seed doesn't run the previously ran migrations anymore

### ISSUE THREAD

**Issue by suthanbala** [pboling/seed_migration#54]
**Scenerio**
- I have two migrations, `20170301193307_initial_seed.rb` and `20170309193307_addmedia_thumbnail_sizes.rb`.
- The `seeds.rb` file has this as the timestamp `SeedMigration::Migrator.bootstrap(20170309193307)`
- When I do `rake db:reset` and then `rake seed:migrate`, it doesn't run the migrations.

From my understanding, how this gem works is, it pulls the migration files' contents and append them into the `seeds.rb`, that way it doesn't need to run through each migrations anymore. However, the `seeds.rb` doesn't have any code appended to the transaction.

**Comment by pjambet** [comment]
Thanks for this other bug report.

As as I said in #53 , I don't have a lot of time, but feel free to send a PR, I will happily review it.

Thanks again!

**Comment by pboling** [comment]
I think the timestamp matching your last seed is preventing it from running again.  The timestamp is how it keeps track of what still needs to run.
```
SeedMigration::Migrator.bootstrap(20170309193307)
```
It's essentially the same with regular DB migrations.

**Comment by pboling** [comment]
May be the same as #51
