### ISSUE TITLE
Incompatible with Sorcery

### ISSUE THREAD

**Issue by marnen** [pboling/seed_migration#55]
I'm having difficulty getting this gem to not step on the toes of [Sorcery](/Sorcery/sorcery) in a Rails 4.1 application. Here's what I've found:

* If I have the seed_migration initializer loading before the Sorcery initializer, then `SeedMigration.register User` prevents the Sorcery modules from being included in the User class.
* If I have the seed_migration initializer loading _after_ the Sorcery initializer, then `SeedMigration.register User` triggers the Sorcery modules before they're fully configured (which happens in `Rails.application.config`), which makes Sorcery throw an error.
* If I load the seed_migration initializer after Rails application configuration (i.e. at the end of config/environment.rb), Sorcery loads properly but `SeedMigration.register User` doesn't register the User model.

Help?

**Comment by pjambet** [comment]
Hi,

Sorry for the late reply, I don't exactly know what I changed but I apparently muted the notifications from this repo by mistake and didn't notice new issues opened in the last 6 months. Sorry about that.

I've never used Sorcery so I don't have a lot of context but I'll see if I can help, but I don't have a lot of available time, so I can't make any promises.
