### ISSUE TITLE
Testing Migration

### ISSUE THREAD

**Issue by vovkats** [pboling/seed_migration#60]
@pjambet How can I test migration via rspec or minitest ?

**Comment by pjambet** [comment]
Hi @vovkats ,

I'm not exactly sure I understand what you're asking for?

Are you trying to make sure that running `rake db:seed` would work correctly?

If so, I believe you should be able to write specs with any frameworks and manually run the task with:

```ruby
Rake::Task["seed:migrate"].execute
```

I believe you'll need to have the rails environment loaded for the rake task to be defined, which should be automatic if using something like `rspec-rails`

**Comment by pboling** [comment]
I think the question is, "can I unit test the seed migration itself?" - that's an interesting question, but not going to look into it right now.
