### ISSUE TITLE
Support other ORMs (Sequel)

### ISSUE THREAD

**Issue by gxespino** [pboling/seed_migration#64]
Any plans to provide support for other ORMs, namely Sequel (https://github.com/jeremyevans/sequel)?

**Comment by pjambet** [comment]
Hi @gxespino,

This is not on our roadmap since we aren't using this as actively as we used to. That being said I think it could be a great addition to the gem and you're more than welcome to open a PR if you want to!

**Comment by pboling** [comment]
PRs welcome!  Closing for now.
