### ISSUE TITLE
Rails 5.2 compatibility issue with db:setup/db:create

### ISSUE THREAD

**Issue by timhaines** [pboling/seed_migration#66]
Rails 5.2 changed db:create process to include the environment, meaning initializers run before db:create is execute.  If you have `SeedMigration.register` in an initializer it will raise an error.

We've worked around it by checking for the existence of the database before calling `SeedMigration.register` in the initializer.

**Comment by pjambet** [comment]
Hi @timhaines ,

Thank you for reporting this, that being said, a quick update on my end. I no longer work at Harry's so I won't be able to help from now on.

As far as I know this gem is no longer in use there, so I am not sure if this will be addressed.

**Comment by pboling** [comment]
@pjambet we use this gem extensively at @rivierapartners.  I'm interested in taking over the gem's maintenance.  @harrystech - if you are no longer using the gem, would yo consider passing it to a new home?

**Comment by pboling** [comment]
https://github.com/harrystech/seed_migration/issues/69

**Comment by pboling** [comment]
Need to determine if this is still an issue with Rails 6 / 7

**Comment by pboling** [comment]
Fixed by #68
