### ISSUE TITLE
Rails 7 Support

### ISSUE THREAD

**Issue by snex** [pboling/seed_migration#74]
Is this no longer being maintained? If not, please pass it to somebody who will maintain it.

**Comment by pboling** [comment]
Hi @snex, I became the new maintainer last year, and haven't had a chance to dig into updating it, while the project I had that utilized this gem is no longer running, so the personal urgency disappeared for me.  Happy to review PRs, and add more maintainers!  Would be happy to turn this into an org and hand off to community.

**Comment by pboling** [comment]
Copying from your other issue:

```
** Invoke seed:migrate:status (first_time)
** Invoke environment (first_time)
** Execute environment
** Execute seed:migrate:status
rake aborted!
NoMethodError: undefined method `connection_config' for ActiveRecord::Base:Class
Did you mean?  connection_db_config
               connection_pool
               connection_class
               connection_class=
               connection_class?
```

**Comment by pboling** [comment]
@snex Please see #68 which I just merged, and see if that fixes it for you.

**Comment by pboling** [comment]
From the description of #68 it sounds like the same issue, so I'm going to assume it is fixed until it is reported again.
